from data.bosses import formation_name
from constants.objectives.condition_bits import NameBit

boss_objective_ids = [
    formation_name["Air Force"],
    formation_name["Atma"],
    formation_name["AtmaWeapon"],
    formation_name["Chadarnook"],
    formation_name["Cranes"],
    formation_name["Dadaluma"],
    formation_name["Doom"],
    formation_name["Doom Gaze"],
    formation_name["Dullahan"],
    formation_name["FlameEater"],
    formation_name["GhostTrain"],
    formation_name["Goddess"],
    formation_name["Guardian"],
    formation_name["Hidon"],
    formation_name["Ifrit/Shiva"],
    formation_name["Inferno"],
    formation_name["Kefka (Narshe)"],
    formation_name["Leader"],
    formation_name["MagiMaster"],
    formation_name["Nerapa"],
    formation_name["Number 024"],
    formation_name["Number 128"],
    formation_name["Phunbaba 3"],
    formation_name["Phunbaba 4"],
    formation_name["Poltrgeist"],
    formation_name["Rizopas"],
    formation_name["SrBehemoth"],
    formation_name["Stooges"],
    formation_name["Tentacles"],
    formation_name["Tritoch"],
    formation_name["TunnelArmr"],
    formation_name["Ultros 1"],
    formation_name["Ultros 2"],
    formation_name["Ultros 3"],
    formation_name["Ultros/Chupon"],
    formation_name["Umaro"],
    formation_name["Vargas"],
    formation_name["Whelk"],
    formation_name["Wrexsoul"],
    formation_name["Marshal"],
]
